//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace g3gh.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("g3-gh.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_01 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_02 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_03 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_04 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_05 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_06 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_07 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_08 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_09 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_10 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_11 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_12 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_13 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_14 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_15 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_16 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_17 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_18 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_19 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_20 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_21 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_22 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_23 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_24 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_25 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_26 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_27 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_28 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_29 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_30 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_31 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_32 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_33 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_34 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_35 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_36 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_37 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_38 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_39 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_40 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_41 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_42 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_43 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_44 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_45 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_46 {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
