//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace g3gh {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("g3-gh.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_01_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_01_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_02_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_02_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_03_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_03_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_04_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_04_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_05_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_05_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_06_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_06_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_07_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_07_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_08_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_08_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_09_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_09_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_10_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_10_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_11_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_11_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_12_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_12_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_13_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_13_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_14_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_14_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_15_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_15_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_16_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_16_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_17_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_17_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_18_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_18_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_19_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_19_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_20_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_20_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_21_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_21_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_22_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_22_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_23_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_23_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_24_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_24_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_25_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_25_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_26_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_26_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_27_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_27_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_28_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_28_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_29_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_29_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_30_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_30_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_31_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_31_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_32_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_32_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_33_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_33_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_34_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_34_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_35_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_35_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_36_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_36_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_37_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_37_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_38_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_38_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_39_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_39_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_41_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_41_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_42_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_42_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_43_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_43_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g3_gh_icons_44_copy {
            get {
                object obj = ResourceManager.GetObject("g3_gh_icons_44_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
